
<?php
    echo "<pre>";
    echo "        ^";
    echo "<br>";
    echo "        +";
    echo "<br>";
    echo "       +++";
    echo "<br>";
    echo "      +++++";
    echo "<br>";
    echo "     *=====*";
    echo "<br>";
    echo "     |*   *|";
    echo "<br>";
    echo "     | * * |";
    echo "<br>";
    echo "     |  *  |";
    echo "<br>";
    echo "     | * * |";
    echo "<br>";
    echo "     |*   *|";
    echo "<br>";
    echo "     *=====*";
    echo "<br>";
    echo "    +|*   *|+";
    echo "<br>";
    echo "   + | * * | +";
    echo "<br>";
    echo "  +  |  *  |  +";
    echo "<br>";
    echo " +   | * * |   +";
    echo "<br>";
    echo "+    |*   *|    +";
    echo "<br>";
    echo "-----*=====*-----";
    echo "<br>";
    echo "   ^^^^^^^^^^^";
    echo "<br>";
    echo "    ^^^^^^^^^";
    echo "<br>";
    echo "      ^^^^^";
    echo "<br>";
    echo "        ^";
?>